---
- name: Install nginx Web Server
  become: true
  ansible.builtin.package:
    name:
      - 'nginx'

- name: Copy nginx config
  become: true
  ansible.builtin.copy:
    src: "files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy nginx site-config
  ansible.builtin.template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/sites-available/nginx.conf"
    owner: root
    group: root
    mode: '0644'

- name: Link sites-available to sites-enable
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/nginx.conf"
    dest: "/etc/nginx/sites-enabled/nginx.conf"
    owner: root
    group: root
    state: link
