---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Install UFW Firewall
  become: true
  ansible.builtin.package:
    name:
      - 'ufw'
- name: Allow ssh
  become: true
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow http
  become: true
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Deny https
  become: true
  community.general.ufw:
    rule: deny
    port: '443'
    proto: tcp

- name: Enable ufw
  become: true
  community.general.ufw:
    state: enabled
