---
- name: Allow ssh
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow http
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow https
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable ufw
  community.general.ufw:
    state: enabled
